
# Command Registers
LPMS_ACK                    = 0
LPMS_NACK                   = 1

LPMS_UPDATE_FIRMWARE        = 2
LPMS_UPDATE_IAP             = 3

LPMS_GET_CONFIG             = 4
LPMS_GET_STATUS             = 5

LPMS_GOTO_COMMAND_MODE      = 6
LPMS_GOTO_STREAM_MODE       = 7
#LPMS_GOTO_SLEEP_MODE        = 8
LPMS_GET_SENSOR_DATA        = 9
LPMS_SET_TRANSMIT_DATA      = 10
LPMS_SET_STREAM_FREQ        = 11
LPMS_WRITE_REGISTERS        = 15
LPMS_RESET_FACTORY_VALUE    = 16
LPMS_SET_ORIENTATION_OFFSET = 18
LPMS_RESET_ORIENTATION_OFFSET = 82
LPMS_SET_FILTER_MODE        = 41
LPMS_SET_IMU_ID             = 20
LPMS_SET_ACC_RANGE          = 31


RESTORE_FACTORY_VALUE       = 16

GET_FIRMWARE_VERSION        = 47
SET_TIME_STAMP              = 66

LPMS_SET_LPBUS_DATA_MODE    = 75


GET_BATTERY_LEVEL           = 87
GET_BATTERY_VOLTAGE         = 88
GET_CHARGING_STATUS         = 89

SET_DEVICE_NAME             = 91
GET_DEVICE_NAME             = 92

SET_LED_COLOR               = 93
GET_LED_COLOR               = 94
SET_LED_WAVEFORM            = 95

START_SYNC                  = 96
STOP_SYNC                   = 97
GET_PING                    = 98

GET_TEMPERATURE             = 99

# Debug Flash Logging
START_DEBUG_LOGGING         = 110
STOP_DEBUG_LOGGING          = 111
CLEAR_DEBUG_LOG             = 112
FULL_FLASH_ERASE            = 113
GET_DEBUG_LOGGING_STATUS    = 114
GET_DEBUG_LOG_SIZE          = 117
GET_DEBUG_LOG               = 118


LPMS_LPBUS_DATA_MODE_32     = 0
LPMS_LPBUS_DATA_MODE_16     = 1

LPMS_ORIENTATION_RESET_OBJECT       = 0
LPMS_ORIENTATION_RESET_HEADING      = 1
LPMS_ORIENTATION_RESET_ALIGNMENT    = 2

LPMS_STREAM_FREQ = {
    0: 5,
    1: 10,
    2: 25,
    3: 50,
    4: 100,
    5: 200,
    6: 400,
}
LPMS_STREAM_FREQ_5HZ    = 5
LPMS_STREAM_FREQ_10HZ   = 10
LPMS_STREAM_FREQ_25HZ   = 25
LPMS_STREAM_FREQ_50HZ   = 50
LPMS_STREAM_FREQ_100HZ  = 100
LPMS_STREAM_FREQ_200HZ  = 200
LPMS_STREAM_FREQ_400HZ  = 400